### PR TITLE
Simplified Chinese language for the ubport app

### PR DESCRIPTION
**Pull request by mutse**
EN：Simplified Chinese language for the ubport app
zh_CN：ubport app 简体中文语言

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Thx for the translation @mutse.

Is it safe to merge po files @Flohack74 or will this kill Weblate?

**Comment by Flohack74** [comment]
This will kill Weblate xD => The po can probably be imported in Weblate directly let me see...

**Comment by Flohack74** [comment]
Correction: It *should* work, as the Chinese po is not in Weblate now. Lets try, go ahead & merge it

**Comment by NeoTheThird** [comment]
done

**Pull request merged**
