### PR TITLE
Remove duplication

### PR DESCRIPTION
**Pull request by krille-chan**
# Description of the Change

This error causes that you are no longer able to compile this app. So I have removed all duplications.
# Benefits

Now its possible again to run the app with clickable.
# Possible Drawbacks

Maybe the chinese translation needs now a new review.

Related Issues: #38

### CODE REVIEW

**Comment by NeoTheThird** [comment]
We good @Flohack74?

**Comment by Flohack74** [comment]
Probably yes, but there are also some strings changed besides the removed duplication. I am not sure where this comes from. We just need to be careful not to revert new translations. Did you rebase this to master @ChristianPauly ?

**Comment by ChristianPauly** [comment]
Sorry, I have forgotten to rebase it to the current version. Now it is only removed the lines which are duplicated and I have tested that it is now working with clickable again

**Comment by bhdouglass** [comment]
@Flohack74 good now?

**Pull request merged**
